# Generated by Django 4.2.3 on 2023-07-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_user_alter_comment_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
